export const FIJAR_DIA = 'FIJAR_DIA'
export const FIJAR_PAIS = 'FIJAR_PAIS'
export const FIJAR_DESTINO = 'FIJAR_DESTINO'
export const FIJAR_DATOS_REGION = 'FIJAR_DATOS_REGION'
export const PLAY = 'PLAY'

export const CERRAR_BANDEJA = 'CERRAR_BANDEJA'
export const ABRIR_BANDEJA = 'ABRIR_BANDEJA'